### ISSUE TITLE
deserialization into structs always visits every header field

### ISSUE THREAD

**Issue by adwhit** [BurntSushi/rust-csv#87] opened 2017-08-27 10:48 UTC
See investigation into slow deserialization here:

https://users.rust-lang.org/t/time-for-performance-optimization/12568/4

**Comment by BurntSushi** [comment] 2017-08-27 13:45
There isn't enough data here for me to do anything about. I read your comment, but I don't have time to dissect a program like that. So I tried to reproduce just the csv parsing part. I downloaded [`data_Q2_2017.zip`](https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q2_2017.zip) from [backblaze](https://www.backblaze.com/b2/hard-drive-test-data.html), unzipped the archive and concatenated all of the files into one:

```
$ xsv cat rows *.csv > /tmp/all.csv
```

I then established a baseline on `all.csv` by seeing how long it takes `xsv` to count all of the records:

```
$ time xsv count /tmp/all.csv 
7568630

real    0m5.037s
user    0m4.793s
sys     0m0.243s
```

I then wrote a simple program that deserializes each record into a struct. I copied the struct definition from the linked thread and changed the type of `capacity` from `u64` to `i64`, since apparently some of its values can be negative. Here's the code:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::env;

#[allow(dead_code)]
#[derive(Deserialize)]
struct Record {
    #[serde(rename = "serial_number")]
    serial: String,
    model: String,
    #[serde(rename = "capacity_bytes")]
    capacity: i64,
    failure: u8
}

fn main() {
    let path = env::args_os().nth(1).unwrap();
    let mut rdr = csv::Reader::from_path(path).unwrap();

    let mut count = 0i64;
    for result in rdr.deserialize() {
        let record: Record = result.unwrap();
        count = count.wrapping_add(record.capacity);
    }
    println!("capacity count: {:?}", count);
}
```

I then compiled and ran this on the `all.csv` file created above:

```
$ time ./target/release/csv-87 /tmp/all.csv 
capacity count: -2177237517030928870

real    0m10.391s
user    0m10.128s
sys     0m0.263s
```

That's twice as slow as just counting the records. Instinctively, that *feels* about right. Looking at a profile of the aforementioned program doesn't show anything amiss.

I then tried your proposed fix, which was to trim the header down. Here's the code:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::env;

#[allow(dead_code)]
#[derive(Deserialize)]
struct Record {
    #[serde(rename = "serial_number")]
    serial: String,
    model: String,
    #[serde(rename = "capacity_bytes")]
    capacity: i64,
    failure: u8
}

fn main() {
    let path = env::args_os().nth(1).unwrap();
    let mut rdr = csv::Reader::from_path(path).unwrap();
    let header = rdr.headers().unwrap().iter().take(5).collect();

    let mut count = 0i64;
    for result in rdr.records() {
        let row = result.unwrap();
        let record: Record = row.deserialize(Some(&header)).unwrap();
        count = count.wrapping_add(record.capacity);
    }
    println!("capacity count: {:?}", count);
}
```

And here's the run:

```
$ time ./target/release/csv-87 /tmp/all.csv 
capacity count: -2177237517030928870

real    0m7.717s
user    0m7.456s
sys     0m0.261s
```

This does indeed strike me as a little odd. To rule out any other funny business, I changed this line:

```rust
let header = rdr.headers().unwrap().iter().take(5).collect();
```

to

```rust
let header = rdr.headers().unwrap().iter().collect();
```

with the rest of the code remaining the same. The run for that change is:

```
$ time ./target/release/csv-87 /tmp/all.csv 
capacity count: -2177237517030928870

real    0m11.806s
user    0m11.558s
sys     0m0.247s
```

So there's clearly a performance cost to using a long header row that you don't need. However, there is no pathological case happening here or any `O(n^2)` behavior. If we look at a profile, we can see that there is quite a bit more time being spent iterating over the fields in a record. Indeed, if you think about what the automatic deserialization code would look like, it is probably iterating over every possible field and setting the appropriate members on the struct. If you take a look at the [Serde example here](https://serde.rs/deserialize-struct.html), then assuming that roughly corresponds to the generated code, we can see that it will read every field in the header (which is enumerated by `next_key`) for every single record. The obvious optimization is to quit reading keys once all struct members have been populated, but I imagine this can't be done in the general case. The CSV case is somewhat special because the header applies to every single row, where as in a format like JSON, it is important to visit every key in order to successfully parse the data.

I'm not really sure what my advice is here. "The CSV crate is slow on wide data" is, at best, an incomplete story. Basically, in order to hit this case you need all of the following to be true:

1. You want automatic deserialization.
2. You want a very small number of columns in the CSV data, where the number of available columns is much larger.
3. The columns you want are *all* at the beginning of each record. (If you wanted a column towards the end of a record, then you'd need to visit each column until you got to the one you wanted.)

In general, this feels somewhat niche, and I'm not sure it's worth attempting to fix this. If we were going to fix this, I'd imagine `serde_derive` would need to grow some option to cause it to stop asking for keys once all members of a struct have been populated. This is safe to do for CSV parsing. (cc @dtolnay)

With that said, the optimization you applied here works pretty well, and I'm happy to see that it is possible to do at all. :-) At the very least, we can add an example like this to the cookbook.

**Comment by BurntSushi** [comment] 2017-08-27 13:47
Bonus round. To make this go even faster (while keeping automatic deserialization), you can amortize the allocation done on records. Here's the code:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::env;

#[allow(dead_code)]
#[derive(Deserialize)]
struct Record {
    #[serde(rename = "serial_number")]
    serial: String,
    model: String,
    #[serde(rename = "capacity_bytes")]
    capacity: i64,
    failure: u8
}

fn main() {
    let path = env::args_os().nth(1).unwrap();
    let mut rdr = csv::Reader::from_path(path).unwrap();
    let header = rdr.headers().unwrap().iter().take(5).collect();
    let mut row = csv::StringRecord::new();

    let mut count = 0i64;
    while rdr.read_record(&mut row).unwrap() {
        let record: Record = row.deserialize(Some(&header)).unwrap();
        count = count.wrapping_add(record.capacity);
    }
    println!("capacity count: {:?}", count);
}
```

And the run:

```
$ time ./target/release/csv-87 /tmp/all.csv 
capacity count: -2177237517030928870

real    0m6.827s
user    0m6.590s
sys     0m0.237s
```

12% is a not a huge boost, but it's not nothing either. :-)

**Comment by BurntSushi** [comment] 2017-08-27 13:49
(It's also worth mentioning that Serde is being super awesome here. The fact that we can do automatic deserialization on such a huge CSV file while *almost* paying only for what we want is really cool. Usually automatic deserialization is much slower than just counting records, but since we're only deserializing a small percentage of the number of columns, the difference ends up being quite smaller in this case.)

**Comment by adwhit** [comment] 2017-08-27 14:19
Interesting. Thanks for the investigation and explanation! The fact that any of this stuff is possible is pretty amazing really.

**Comment by BurntSushi** [comment] 2018-01-30 13:50
Thanks for reporting this issue, but I am going to close it. I don't think there is anything super actionable that the `csv` crate can do here and I don't have the bandwidth to push on serde to do anything.

**Closed by BurntSushi** 2018-01-30 13:50 UTC
