### ISSUE TITLE
Optional columns and serde

### ISSUE THREAD

**Issue by veldsla** [BurntSushi/rust-csv#113] opened 2018-05-15 14:07 UTC
Im trying to read and write a flexible csv file using serde for (de)serialization. I use this struct:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct Test {
    name: String,
    start: u64,
    stop: u64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    stuff: Vec<String>
}
```
If I write the following structs I get the expected output
```rust
Test { name: "one".to_owned(), start: 1, stop: 10, stuff: Vec::new() }
Test { name: "two".to_owned(), start: 2, stop: 10, stuff: vec!["it".to_owned(), "does".to_owned()] }
```
```
one,1,10
two,2,10,it,does
```
Unfortunately I'm unable to read such a file:
```
Err(Error(Deserialize { pos: Some(Position { byte: 0, line: 1, record: 0 }), err: DeserializeError { field: None, kind: Message("invalid length 3, expected struct Test with 4 elements") } }))
```
I was hoping the `#[serde(default)]`would take care of that. Any way I can make this work?
Example as program: https://gist.github.com/veldsla/2f62691f8e20b6f00c5152a83ae63cea

**Comment by BurntSushi** [comment] 2018-05-15 14:14
This looks like a duplicate of #110. The workaround is to use `Option<Vec<String>>`. I think I would in principle agree with fixing this bug, but I don't know how. Ideas are welcome.

**Comment by BurntSushi** [comment] 2018-05-15 14:42
Interesting. I don't know. Someone needs to dive into the Serde integration to figure out whether there is a way to work-around this.

**Comment by BurntSushi** [comment] 2019-02-21 16:57
This looks like a dupe of #145. Serde support and "flexible" parsing do not mix well.

**Closed by BurntSushi** 2019-02-21 16:57 UTC

**Comment by agoston** [comment] 2022-07-23 08:53
I bumped into the same issue; flexible is enabled and yet I'm getting this Error:

```
DeserializeError { field: None, kind: Message("invalid length 3, expected struct ApiTransaction with 4 elements") } }
```

There is even an example in front of `ReaderBuilder.flexible()` that would indicate that this feature does work.
Is this ever going to get fixed?

**Comment by BurntSushi** [comment] 2022-07-23 10:47
Flexible applies the csv record length. It doesn't apply to serde deserialization.

Why not share which doc example you're referring to?

> Is this ever going to get fixed?

FYI, this comes across as pretty rude.

**Comment by agoston** [comment] 2022-07-23 12:18
Sorry, I didn't mean it that way. This is a great lib and I'm grateful that you spend your free time on providing this for free.

I've checked the examples once more, and they indeed use `.records()`, not `.deserialize()`, so then it works.

It's just that I'm in a lot of pain right now, as I invested heavily into serde-based deserialization, which now I can throw away, because I did not spot this deficiency in time. Do you think it would help others to make this clearer in the documentation?

**Comment by BurntSushi** [comment] 2022-07-23 13:00
Better docs are always welcome.

I'm sure there is a workaround. Like defining distinct types for each record length and deserializating into the right type based on record length.

**Comment by jrouaix** [comment] 2023-07-29 17:24
Hello, 
I don't know if someone still struggling with this issue but I also went into, 
and found a workaround so let's post it here to help other.

so you can get the `StringRecord` and add more fields when needed like 
```rust
for result in reader.records() {
  let mut fields = result?;
  for _ in fields.len()..THE_FIELDS_COUNT_YOU_NEED {
    fields.push_field("");
  }
  let my_struct = fields.deserialize::<MyStruct>()?; // it won't fail for missing fields !
  // ....
}
```

Not very proud but working, let me know if you find a better way !
