### ISSUE TITLE
Reader not ignoring commas inside quoted strings.

### ISSUE THREAD

**Issue by Bietola** [BurntSushi/rust-csv#181] opened 2019-11-11 13:01 UTC
Hello everyone,

I am using version 1.1.1.

I am trying to parse csv records that contain commas inside their strings.

In an attempt at isolating the problem, I've come up with this example:

``` rust
extern crate csv;

use std::collections::HashMap;

fn main() {
    let rdr = csv::ReaderBuilder::new().from_path("example").unwrap();

    let test_map: HashMap<_, _> = rdr
        .into_deserialize()
        .map(|result| -> (String, String) { result.unwrap() })
        .collect();

    println!("{:?}", test_map);
}
```

In which I try to parse the `example` file, shown below:

```
name, last_name
Fede, "red beard, II"
S`tefano, "great, I"
Dani, "crazy, IX"
```

Upon calling the `cargo run` command, the program immediately panics with the fallowing message: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(UnequalLengths { pos: Some(Position { by
te: 16, line: 2, record: 1 }), expected_len: 2, len: 3 })', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I think this is because the comma inside of the quoted strings is interpreted as a separator and not escaped. Is there a way to escape the separator (I've tried with `\,` and `,,`, but both don't seem to work) or to configure the Reader to ignore it if is found inside quoted strings?

**Comment by BurntSushi** [comment] 2019-11-11 13:06
Your CSV data is malformed. You can't have spaces between your quotes and your commas. Python interprets your data in exactly the same way:

```
>>> import csv
>>> for r in csv.DictReader(open('/tmp/data.csv')):
...     print(r)
...
...
OrderedDict([('name', 'Fede'), (' last_name', ' "red beard'), (None, [' II"'])])
OrderedDict([('name', 'S`tefano'), (' last_name', ' "great'), (None, [' I"'])])
OrderedDict([('name', 'Dani'), (' last_name', ' "crazy'), (None, [' IX"'])])
```

Incidentally, this is a duplicate of #180.

**Closed by BurntSushi** 2019-11-11 13:06 UTC

**Comment by fstephany** [comment] 2020-04-10 15:00
I had a hard time understanding the answer. 
To clarify for the next me reading this issue, the quotes should be right after the separator (ie., `Fede," red bear, II"` instead of `Fede, "red bear, II"`):

~~~csv
name, last_name
Fede,"red beard, II"
S`tefano,"great, I"
Dani,"crazy, IX"
 ~~~

~~~
>>> for r in csv.DictReader(open('/tmp/data.csv')):
...   print(r)
... 
OrderedDict([('name', 'Fede'), (' last_name', 'red beard, II')])
OrderedDict([('name', 'S`tefano'), (' last_name', 'great, I')])
OrderedDict([('name', 'Dani'), (' last_name', 'crazy, IX')])
~~~
