### ISSUE TITLE
feature: allow erroring on unterminated quoted fields

### ISSUE THREAD

**Issue by sploiselle** [BurntSushi/rust-csv#252] opened 2021-11-02 14:49 UTC
#### What version of the `csv` crate are you using?

csv = "1.1.6"

#### Briefly describe the question, bug or feature request.

The CSV library allows unterminated quotes in its input without raising an error, or letting users opt in to errors on this input.

#### Include a complete program demonstrating a problem.

Apply this diff to `master`:

```diff
diff --git a/examples/data/smallpop.csv b/examples/data/smallpop.csv
index b071c25..c12835b 100644
--- a/examples/data/smallpop.csv
+++ b/examples/data/smallpop.csv
@@ -8,4 +8,4 @@ Springfield,MO,United States,150443
 Springfield,NJ,United States,14976
 Springfield,OH,United States,64325
 Springfield,OR,United States,56032
-Concord,NH,United States,42605
+Concord,NH,United States,"42605
```

And then run the example:

```shell
cargo run --example cookbook-read-basic < examples/data/smallpop.csv
```

#### What is the observed behavior of the code above?

```
StringRecord(["Southborough", "MA", "United States", "9686"])
StringRecord(["Northbridge", "MA", "United States", "14061"])
StringRecord(["Westborough", "MA", "United States", "29313"])
StringRecord(["Marlborough", "MA", "United States", "38334"])
StringRecord(["Springfield", "MA", "United States", "152227"])
StringRecord(["Springfield", "MO", "United States", "150443"])
StringRecord(["Springfield", "NJ", "United States", "14976"])
StringRecord(["Springfield", "OH", "United States", "64325"])
StringRecord(["Springfield", "OR", "United States", "56032"])
StringRecord(["Concord", "NH", "United States", "42605\n"])
```

#### What is the expected or desired behavior of the code above?

Something akin to:
```
error running example: CSV error: record 10 (...): unterminated quoted field
```

**Comment by BurntSushi** [comment] 2021-11-02 15:05
> allows unterminated quotes in its input without raising an error

This is by design. As the [docs say](https://docs.rs/csv/1.1.6/csv/struct.Reader.html#error-handling):

> In general, CSV parsing does not ever return an error. That is, there is no such thing as malformed CSV data. Instead, this reader will prioritize finding a parse over rejecting CSV data that it does not understand.

And:

>  letting users opt in to errors on this input

This is dupe of #77.

**Closed by BurntSushi** 2021-11-02 15:05 UTC
