### ISSUE TITLE
feat: support trim in `csv_core`

### ISSUE THREAD

**Issue by youngsofun** [BurntSushi/rust-csv#291] opened 2022-10-24 13:17 UTC
We are using  `csv_core` in our project [databend](https://github.com/datafuselabs/databend),  thank you for your great work!

Currently, trim is done outside  `csv_core`, based on the result of `read_field` or `read_record`.
it works well when there is no quote used in the field.
but leading to 2 kinds of bad cases otherwise.

so I suggest to support trim in `csv_core` directly.

# 1. bad cases

[demo of the problem in rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fadee3357e54fd2c0da1129f98aa579f)

(in this issue, use `|` as field delimiter, use `>value<` to mark the parse result)

## case 1:  spaces inside the quotes should not be removed

`|" foo"|` 

- py(skipinitialspaces=True):: `> foo<` 
- rust csv trim::ALL : `|foo|` (bad case)

 reason: trim is performed after csv-core **removed** `"`

## case 2:   quote immediately after whitespace should be removed 

`| "foo"| `

- py(skipinitialspaces=True): `>foo<`
- rust csv trim::ALL : `>"foo"<` (bad case)

reason: `csv_core` only remove `"` **immediately** after delimiter

# 2. how other lib deal with this

## 2.1 python
the behavior of [python](https://docs.python.org/3/library/csv.html#csv.Dialect.skipinitialspace) seems more reasonable, and consistent

>>> whitespace immediately following the delimiter is ignored

so the `whitespace immediately following the delimiter` is skipped first,  then the remaining is parsed normally.

but in this crate,  the order is reversed.
`| " Hello"|`,  `| Hello|`  both result in `> Hello<`, after read_field (can not distinguish here), but only the whitespace in  `| Hello|` should be trimmed

## 2.2 snowflake
snowflake has the same behavior as python:

```
|"Hello world"|    /* loads as */  >hello world<
|" Hello world "|  /* loads as */  > hello world <
| "Hello world" |  /* loads as */  >hello world<
```

see `TRIM_SPACE` option in https://docs.snowflake.com/en/sql-reference/sql/create-file-format.html#optional-parameters

 FYI:  more discuss in   https://github.com/datafuselabs/databend/issues/8416

**Comment by BurntSushi** [comment] 2022-10-24 15:15
It's hard for me to digest this issue. Could you please provide Rust programs that I can compile and execute, along with input, actual output and desired output?

**Comment by youngsofun** [comment] 2022-10-25 00:56
[demo of the problem in rust play ground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fadee3357e54fd2c0da1129f98aa579f)

**Comment by BurntSushi** [comment] 2022-10-25 02:13
OK, thanks. That is intended behavior. Your CSV data is weird, because it's inserting spaces _before_ the quotes. Your CSV data is technically malformed, so _that's_ what should be fixed. The `csv` crate is just giving you a parse because it's designed to never return an error in case you can't fixed your data.

The other problem is that it looks like you're not expecting data _inside_ the quotes to be trimmed? That doesn't make any sense to me. The point of trimming is to get rid of whitespace around the value itself. What you're talking about is modifying the parser's semantics themselves (hence the reference to Python's "dialect" option). That's orthogonal to the csv crate's "trim" option.

Personally, I don't see any good reason for supporting Python's "skip initial space" option. You linked to https://github.com/datafuselabs/databend/issues/8416, but I don't see any high level motivation for the problem.

**Comment by youngsofun** [comment] 2022-10-25 03:02
thanks for your quick reply.

I totally understand what you mean, it`s ok to not change the behavior, just a little more explanation (forgive my poor English): 

difference of opinion comes from what `trim` is intended for:

Usage 1:  
---

1. CSV should be "standard" to RFC: no additional spaces should be added
2. trim the real user data value, just because user are not interested in it.

I think this can be easily handled by the user himself.

Usage 2 (python, snowflake, spark):
--

the CSV file is not strict,  the spaces are added in by the writer program, and must be trimmed to correctly read it.

e.g. maybe not generated by Excel or CSV library, but manually like the following python code.

```python
", ".join(map(fields, quote_it))
```
There are other historical reasons I do not know for these libs to support this. 

there are also some more examples in https://en.wikipedia.org/wiki/Comma-separated_values  (search "spaces")

Maybe it is more important for a CSV library to load used as it is (although not standard) than to change it(Usage 1).
If there are such demands, may be relatively hard for users to deal with, but they have to.  

 I don`t like this feature too, but since we are implementing a database,  I try this also to check if one day the user needs `usage 2`, we can support it quickly (maybe with my own patched branch).

----

is it acceptable to you to make this an optional feature of the crate?

**Comment by BurntSushi** [comment] 2022-10-25 03:08
If there's no concrete use case for it, then I'm no, I'm not inclined to add it at all. Supporting naive attempts to write CSV data like `", ".join(map(fields, quote_it))` is really just not good enough.

I mean, this is a super niche feature. You have to opt into it when using Python AFAIK too. I've studied the Python CSV parser quite extensively, and even I didn't know about it until you made me aware of it in this issue.

**Closed** 2022-10-25 03:14 UTC
