### ISSUE TITLE
Empty strings inside a flattened Option<String> don't result in None

### ISSUE THREAD

**Issue by jkcclemens** [BurntSushi/rust-csv#131] opened 2018-09-12 13:13 UTC
See title. For example, if I have a CSV like this

```csv
First,Last,Preferred,SomethingElse
James,Jones,Jim,1
Bob,Bobson,,1
```

and a structure like this

```rust
#[derive(Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Entry {
  #[serde(flatten)]
  names: Names,
  something_else: u8,
}

#[derive(Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Names {
  first: String,
  last: String,
  preferred: Option<String>,
}
```

the result on deserialisation is that Bob Bobson's preferred name will be `Some("")` instead of `None`.

If the structure unflattens and removes the `Names` struct, the preferred name for Bob Bobson will be `None`.

In case that's not clear enough, I made a [Rust Playground](https://play.rust-lang.org/?gist=2e36fd37c6dd53dc1fe188faeeab96c9&version=stable&mode=debug&edition=2015) link that shows the problem.

**Comment by BurntSushi** [comment] 2018-09-12 13:38
Dupe of #114.

This is intended and correct behavior. If you want to treat empty strings as `None` values, then it should be possible to write a custom deserialize_with function that does it for you.

**Closed by BurntSushi** 2018-09-12 13:38 UTC
Labels: duplicate

**Comment by jkcclemens** [comment] 2018-09-12 14:02
It doesn't look like a dupe of #114. How I understand it, 114 is saying that `,,` and `,"",` should return different values (`None`, and `Some("")`, respectively). This issue is about inconsistent behaviour on flattened structs.

The same data deserialises an `Option<String>` field into `None` without a flattened struct and into `Some("")` with a flattened struct.

If it's intended that flattening a struct changes the result, then that's fine, though I would disagree with that practice.

**Comment by BurntSushi** [comment] 2018-09-12 14:17
Oh interesting. I did not look closely enough to catch that. AIUI, flattening is done on serde's side and should impact the semantics of deserialization like this, so I'd say it might be a bug in serde. But I haven't had a chance to dig into this yet.
