### ISSUE TITLE
Example cookbook-read-serde failing standalone

### ISSUE THREAD

**Issue by gorn** [BurntSushi/rust-csv#124] opened 2018-07-31 16:29 UTC
Although the example cookbook-read-serde  works when run with the whole repo checked out, it fails when tried standalone. To reproduce

1. create new rust project 
2. put the example code to src/main.rs
3. put the following into Cargo.toml

> 
> [dependencies]
> serde = "1"
> serde_derive = "1"
4. try `cargo run`

it fails with 

> error[E0463]: can't find crate for `_serde`
>   --> trading_game/src/main.rs:11:16
>    |
> 11 | #[derive(Debug,Deserialize)]
>    |                ^^^^^^^^^^^ can't find crate
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0463`.
> error: Could not compile `trading_game`.
> 
> To learn more, run the command again with --verbose.
> 

Maybe I am missing something very obvious, I am very new to rust.

**Comment by gorn** [comment] 2018-07-31 16:46
BTW also the is some mistake on the doc page https://docs.rs/csv/1.0.0/csv/

in text you cite this
```
extern crate serde;
#[macro_use]
extern crate serde_derive;
```
but in the code there is `extern crate csv;`

**Comment by BurntSushi** [comment] 2018-07-31 17:09
Sorry, but I can't seem to reproduce this. Could you please provide more information such as which version of Rust you're using? Could you also show more explicitly the contents of relevant files?

For example, here's my `Cargo.toml`:

```toml
[package]
name = "csv-124"
version = "0.1.0"
authors = ["andrew <jamslam@gmail.com>"]

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
```

Here's my `src/main.rs`:

```rust
extern crate csv;
#[macro_use]
extern crate serde_derive;

use std::error::Error;
use std::io;
use std::process;

// By default, struct field names are deserialized based on the position of
// a corresponding field in the CSV data's header record.
#[derive(Debug,Deserialize)]
struct Record {
    city: String,
    region: String,
    country: String,
    population: Option<u64>,
}

fn example() -> Result<(), Box<Error>> {
    let mut rdr = csv::Reader::from_reader(io::stdin());
    for result in rdr.deserialize() {
        // Notice that we need to provide a type hint for automatic
        // deserialization.
        let record: Record = result?;
        println!("{:?}", record);
    }
    Ok(())
}

fn main() {
    if let Err(err) = example() {
        println!("error running example: {}", err);
        process::exit(1);
    }
}
```

And here's `data.csv`:

```
city,region,country,population
marlborough,ma,us,112343
```

And running:

```
$ cargo run < data.csv
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/csv-124`
Record { city: "marlborough", region: "ma", country: "us", population: Some(112343) }
```

**Comment by BurntSushi** [comment] 2018-08-08 20:17
Folks, I need more information. If I can't reproduce it, then I can't fix it. Please include the full Rust source code, including your `Cargo.toml` along with your Rust and Cargo versions.

**Comment by Caspinol** [comment] 2018-10-02 14:03
@Brainshack you need to add the `extern crate serde;` to the file.

**Comment by BurntSushi** [comment] 2019-04-04 23:06
Closing this because I can't reproduce it.

**Closed by BurntSushi** 2019-04-04 23:06 UTC
Labels: question
