### ISSUE TITLE
Updating vs Overriding csv file

### ISSUE THREAD

**Issue by hasanOryx** [BurntSushi/rust-csv#123] opened 2018-07-21 13:35 UTC
I'm trying to update my csv file using ` let wtr = Writer::from_path('cities.csv');` and `wtr.serialize(&new_record)` below is my code.
I noticed that my code is overriding whatever there in the file, i.e. delete everything in the `cities.csv` file, and insert the new record in it!!
I need to know how to increase the number of records in my file by inserting/writing/amending a new record to it. Thanks

```
use std::error::Error;
use std::env;
use csv::Writer;

use city_model::Record;

pub fn write_csv(csv_file: &str) -> Result<(), Box<Error>> {
    let executable = env::current_exe()?;
    let path = match executable.parent() {
        Some(name) => name,
        _ => panic!()
    };

    let data_file = format!("{}/{}", path.display(), csv_file);

    println!("the data_file name is: {}", data_file);
    let new_record = Record {
            latitude: 456.67,
            longitude: 5675.78,
            population: Some(45768),
            city: "Zaqra".to_string(),
            state: "Jordan".to_string(),
    };
    
    let wtr = Writer::from_path(data_file);
    match wtr {
        Ok(mut t) => match t.serialize(&new_record) {
            Ok(_) => println!("File updated, recordhad been added successfully"),
            Err(e) => panic!("Could not add the record: {:?}", e)
        },
        Err(e) => panic!("Could not open the file: {:?}", e)
    };
    Ok(())
}
```

When I tried `t.write_record(&new_record)` I got the below error:

![rcr](https://user-images.githubusercontent.com/26045838/43036309-ae3699ee-8d07-11e8-9bac-803374cbc67f.png)

My model is defined as below:

```
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Record {
    pub latitude: f64,
    pub longitude: f64,
    pub population: Option<u64>,
    pub city: String,
    pub state: String,
}
```

**Comment by BurntSushi** [comment] 2018-07-21 16:32
Duplicate of #117.

**Closed by BurntSushi** 2018-07-21 16:32 UTC
Labels: duplicate, invalid

**Comment by hasanOryx** [comment] 2018-07-21 16:56
Thanks, but:
`OpenOptions::new().append(true).open(data_file)` returns a `file`, while `tr = Writer::from_path(file_to_append)` requires a `path` so how to mange them together!

**Comment by BurntSushi** [comment] 2018-07-21 16:59
@hasanOryx I **do not** appreciate linking you to a solution only to receive a question in response that is very clearly answered in the solution. It specifically tells you to use `from_writer` and not `from_path`. You cannot use `from_path` to write to a file in append mode.

**Comment by hasanOryx** [comment] 2018-07-21 17:05
I tried it, but not sure wat mistake I do, below my code, and the error msg!

```
    let file_to_append = match OpenOptions::new().append(true).open(data_file){
        Ok(mut f) => f,
        Err(e) => panic!("Could not open the file for appendin: {:?}", e)
    };
    let wtr = Writer::from_writer(file_to_append); 
    match wtr {
        Ok(mut t) => match t.serialize(&new_record)
            {
            Ok(_) => println!("File updated, recordhad been added successfully"),
            Err(e) => panic!("Could not add the record: {:?}", e)
        },
        Err(e) => panic!("Could not open the file: {:?}", e)
    };

```
![wrtr](https://user-images.githubusercontent.com/26045838/43038432-294cd080-8d21-11e8-9d50-52663ec88c44.png)

**Comment by BurntSushi** [comment] 2018-07-21 17:14
I can't help you if you don't show me a complete example.

I think your time would be better spent reading [The Rust Book](https://doc.rust-lang.org/book/second-edition/index.html).

**Comment by hasanOryx** [comment] 2018-07-21 17:16
I already sent you all my code, anyhow, here it is again:

```
use std::error::Error;
use std::env;
use csv::Writer;

use city_model::Record;
use std::fs::OpenOptions;

pub fn write_csv(csv_file: &str) -> Result<(), Box<Error>> {
    let executable = env::current_exe()?;
    let path = match executable.parent() {
        Some(name) => name,
        _ => panic!()
    };

    let data_file = format!("{}/{}", path.display(), csv_file);

    println!("the data_file name is: {}", data_file);
    let new_record = Record {
            latitude: 456.67,
            longitude: 5675.78,
            population: Some(45768),
            city: "Zaqra".to_string(),
            state: "Jordan".to_string(),
    };

    let file_to_append = match OpenOptions::new().append(true).open(data_file){
        Ok(mut f) => f,
        Err(e) => panic!("Could not open the file for appendin: {:?}", e)
    };
    let wtr = Writer::from_writer(file_to_append);
    match wtr {
        Ok(mut t) => match t.serialize(&new_record)
            {
            Ok(_) => println!("File updated, recordhad been added successfully"),
            Err(e) => panic!("Could not add the record: {:?}", e)
        },
        Err(e) => panic!("Could not open the file: {:?}", e)
    };
    Ok(())
}
```

**Comment by BurntSushi** [comment] 2018-07-21 17:50
I see no easy way to compile that code.

**Comment by hasanOryx** [comment] 2018-07-21 17:52
So can you give me direct code, if I've the file name and full path, how the code should be to be able to append to the file there!

**Comment by BurntSushi** [comment] 2018-07-21 18:21
The code:

```rust
extern crate csv;

use std::fs::OpenOptions;

use csv::WriterBuilder;

fn main() -> Result<(), csv::Error> {
    let file = OpenOptions::new().append(true).open("hasan.csv")?;
    let mut wtr = WriterBuilder::new()
        .has_headers(false)
        .from_writer(file);
    wtr.write_record(vec!["northbridge", "ma"])?;
    wtr.flush()?;
    Ok(())
}
```

Example use:

```
$ cat hasan.csv
town,state
southborough,ma
$ cargo run
$ cat hasan.csv
town,state
southborough,ma
northbridge,ma
```

@hasanOryx I'd like to request that you stop asking me questions that are unrelated to this crate. The code you provided above has a compilation error that indicates a type mismatch (`from_writer` returns a `csv::Writer` but you are matching on it as if it were a `Result<csv::Writer, csv::Error>`). There's nothing wrong with making beginner level mistakes, but this issue tracker isn't your personal forum for asking beginner level questions. Please seek out alternative forums, which are listed here: https://www.rust-lang.org/en-US/community.html

**Comment by hasanOryx** [comment] 2018-07-21 19:14
OK @BurntSushi the code you provided worked perfectly with me, but what shall I do if I want to replace the `vec!` in `wtr.write_record(vec!["northbridge", "ma"])?;` by `wtr.write_record(&new_record)?;` this will be last beginner level question here my friend :)

**Comment by BurntSushi** [comment] 2018-07-21 19:15
@hasanOryx Use the [`serialize` method](https://docs.rs/csv/1.0.0/csv/struct.Writer.html#method.serialize).
